site_name: ''

repo_url: https://github.com/thefintz/docs-api

nav:
  - Introdução: 'index.md'
  - Autenticação: 'auth.md'
  - Endpoints:
    - Bolsa B3: 'endpoints/bolsa B3.md'
    - Títulos públicos: 'endpoints/titulos-publicos.md'
    - Fundos de investimento: 'endpoints/fundos de investimento.md'
    - Indices do mercado: 'endpoints/indices do mercado.md'
    - Criptomoedas: 'endpoints/cripto.md'
    - Empresas: 'endpoints/empresas.md'
  - Postman collection: 'postman.md'

theme:
  name: material
  language: pt

  logo: assets/logo-negativo-fundo-preto.png
  favicon: assets/favicon.ico

  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search:
      lang: pt
