site_name: ''

repo_url: https://github.com/thefintz/docs-api

nav:
  - Introdução: 'index.md'
  - Autenticação: 'autenticacao.md'
  - Endpoints:
    - Bolsa: 'endpoints/bolsa.md'
    - Fundos: 'endpoints/fundos.md'
    - Tesouro Direto: 'endpoints/tesouro.md'
    - Índices, Taxas e Câmbio: 'endpoints/indices.md'
    - Point in Time (backtest): 'endpoints/bolsa_point_in_time.md'
  - Postman: 'postman.md'
  - Updates: 'updates.md'
  # - Como calculamos: 'calculos.md'

theme:
  name: material
  language: pt

  logo: assets/logo-negativo-fundo-preto.png
  favicon: assets/favicon.ico

  extra_css:
    - css/custom.css

  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode

markdown_extensions:
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

plugins:
  - search:
      lang: pt