name: Build and deploy

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker compose run --rm -u 0 mkdocs build

      - uses: JamesIves/github-pages-deploy-action@4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: ./site
          single-commit: true
          silent: false
